<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run()
    {
        // Truncate table first to prevent duplicate entries on seed
        $this->db->table('products')->truncate();

        $data = [
            // =========================================================================
            // SUB-KATEGORI: Bambu Hoki (Kategori: Tanaman Hias) - 6 produk
            // =========================================================================
            [
                'name' => 'Bambu Rejeki Fire Ring',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 75000,
                'old_price' => null,
                'image_url' => '/images/products/Bambu Rejeki Fire Ring Clean.png',
                'stock' => 10,
                'rating' => 5.0,
                'reviews_count' => 5,
                'description' => "Bambu Rejeki Fire Ring merupakan tanaman hias bambu hoki dengan susunan batang yang unik dan menarik. Bentuknya yang melingkar memberikan tampilan dekoratif yang berbeda dari bambu hoki biasa, sehingga cocok dijadikan penghias meja, ruang tamu, maupun area kerja.\n\nTanaman ini cocok untuk pelanggan yang menyukai tanaman hias minimalis namun tetap memiliki nilai estetika. Perawatannya cukup mudah karena dapat diletakkan di tempat dengan cahaya tidak langsung dan tidak membutuhkan perawatan yang terlalu rumit.",
            ],
            [
                'name' => 'Bambu Rejeki 3 Tingkat (M)',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 75000,
                'old_price' => null,
                'image_url' => '/images/products/Bambu Rejeki 3 Tingkat (M) Clean.png',
                'stock' => 8,
                'rating' => 4.5,
                'reviews_count' => 12,
                'description' => "Bambu Rejeki 3 Tingkat (M) memiliki bentuk susunan batang bertingkat yang rapi dan elegan. Model bertingkat ini membuat tampilannya terlihat lebih berisi dan cocok digunakan sebagai dekorasi ruangan dengan kesan alami.\n\nProduk ini cocok untuk penghias meja kantor, ruang tamu, maupun hadiah tanaman hias. Selain tampilannya menarik, bambu rejeki juga banyak diminati karena mudah dirawat dan dapat memberikan suasana segar pada ruangan.",
            ],
            [
                'name' => 'Bambu Rejeki Triangle Vas',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 90000,
                'old_price' => null,
                'image_url' => '/images/products/Bambu Rejeki Triangle Vas Clean.png',
                'stock' => 5,
                'rating' => 4.7,
                'reviews_count' => 9,
                'description' => "Bambu Rejeki Triangle Vas merupakan tanaman hias bambu hoki yang disusun dalam bentuk vas segitiga. Bentuk ini memberikan tampilan yang simpel, modern, dan cocok untuk dekorasi indoor.\n\nTanaman ini sesuai untuk pelanggan yang menginginkan tanaman hias berukuran praktis namun tetap menarik. Dengan bentuk yang rapi dan warna hijau alami, produk ini dapat mempercantik sudut ruangan, meja belajar, maupun meja kerja.",
            ],
            [
                'name' => 'Bambu Rejeki Vas Variegata',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 90000,
                'old_price' => null,
                'image_url' => '/images/products/Bambu Rejeki Vas Variegata Clean.png',
                'stock' => 6,
                'rating' => 4.8,
                'reviews_count' => 8,
                'description' => "Bambu Rejeki Vas Variegata memiliki tampilan daun yang lebih menarik karena terdapat variasi warna pada daunnya. Perpaduan warna hijau dan corak variegata membuat tanaman ini terlihat lebih segar dan dekoratif.\n\nProduk ini cocok untuk pelanggan yang menyukai tanaman hias dengan tampilan daun unik. Selain mudah dirawat, Bambu Rejeki Vas Variegata juga dapat menjadi pilihan dekorasi yang memberikan kesan alami dan estetik pada ruangan.",
            ],
            [
                'name' => 'Bambu Rejeki Curly Vas',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 120000,
                'old_price' => null,
                'image_url' => '/images/products/Bambu Rejeki Curly Vas Clean.png',
                'stock' => 4,
                'rating' => 4.9,
                'reviews_count' => 15,
                'description' => "Bambu Rejeki Curly Vas memiliki bentuk batang yang melengkung atau curly sehingga tampil lebih unik dibandingkan bambu hoki biasa. Bentuknya yang artistik membuat tanaman ini cocok sebagai elemen dekorasi modern.\n\nTanaman ini dapat digunakan untuk mempercantik meja, rak, atau sudut ruangan. Dengan perawatan sederhana dan tampilan yang unik, Bambu Rejeki Curly Vas cocok untuk pembeli yang ingin tanaman hias praktis namun tetap menarik perhatian.",
            ],
            [
                'name' => 'Bambu Rejeki Pagoda 5',
                'category' => 'Tanaman Hias',
                'subcategory' => 'Bambu Hoki',
                'price' => 120000,
                'old_price' => 150000,
                'image_url' => '/images/products/Bambu Rejeki Pagoda 5 Clean.png',
                'stock' => 5,
                'rating' => 5.0,
                'reviews_count' => 20,
                'description' => "Bambu Rejeki Pagoda 5 merupakan tanaman bambu hoki dengan susunan batang menyerupai bentuk pagoda. Bentuknya yang bertingkat dan simetris memberikan kesan rapi, unik, serta memiliki nilai dekoratif tinggi.\n\nProduk ini cocok dijadikan dekorasi rumah, kantor, maupun hadiah untuk orang terdekat. Dengan tampilannya yang elegan, Bambu Rejeki Pagoda 5 dapat memberikan nuansa segar sekaligus memperindah ruangan.",
            ],

            // =========================================================================
            // SUB-KATEGORI: Anggrek (Kategori: Tanaman Berbunga) - 6 produk
            // =========================================================================
            [
                'name' => 'Anggrek Bulan Mini Kuning',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 200000,
                'old_price' => null,
                'image_url' => '/images/products/Anggrek Bulan Mini Kuning Clean.png',
                'stock' => 5,
                'rating' => 4.6,
                'reviews_count' => 14,
                'description' => "Anggrek Bulan Mini Kuning merupakan tanaman anggrek berukuran mini dengan warna bunga kuning yang cerah dan lembut. Warna bunganya memberikan kesan segar, ceria, dan cocok untuk mempercantik ruangan maupun teras rumah.\n\nTanaman ini cocok untuk pelanggan yang menyukai anggrek dengan ukuran praktis dan tampilan manis. Dengan perawatan yang tepat, Anggrek Bulan Mini Kuning dapat menjadi koleksi tanaman berbunga yang indah dan menarik.",
            ],
            [
                'name' => 'Anggrek Bulan Mini Putih',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 200000,
                'old_price' => null,
                'image_url' => '/images/products/Anggrek Bulan Mini Putih Clean.png',
                'stock' => 6,
                'rating' => 4.8,
                'reviews_count' => 18,
                'description' => "Anggrek Bulan Mini Putih memiliki bunga berwarna putih yang memberikan kesan bersih, elegan, dan menenangkan. Ukurannya yang mini membuat tanaman ini cocok diletakkan di meja, rak tanaman, atau area indoor dengan pencahayaan cukup.\n\nProduk ini sesuai untuk pelanggan yang menyukai tanaman berbunga dengan tampilan sederhana namun tetap mewah. Warna putih pada bunganya membuat anggrek ini mudah dipadukan dengan berbagai konsep dekorasi rumah.",
            ],
            [
                'name' => 'Cymbidium Chen\'s Ruby',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 175000,
                'old_price' => null,
                'image_url' => '/images/products/Cymbidium Chen\'s Ruby Clean.png',
                'stock' => 4,
                'rating' => 4.9,
                'reviews_count' => 6,
                'description' => "Cymbidium Chen’s Ruby merupakan jenis anggrek dengan tampilan bunga yang menarik dan memiliki karakter berbeda dari anggrek bulan. Bentuk dan warnanya memberikan kesan eksotis sehingga cocok untuk koleksi tanaman berbunga.\n\nTanaman ini cocok untuk pelanggan yang ingin menambah variasi koleksi anggrek di rumah. Dengan bentuk bunga yang khas, Cymbidium Chen’s Ruby dapat menjadi pilihan dekoratif untuk taman, teras, maupun area tanaman hias.",
            ],
            [
                'name' => 'Anggrek Bulan Mini Purple',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 150000,
                'old_price' => null,
                'image_url' => '/images/products/Anggrek Bulan Mini Purple Clean.png',
                'stock' => 10,
                'rating' => 4.7,
                'reviews_count' => 22,
                'description' => "Anggrek Bulan Mini Purple memiliki warna ungu yang cantik dan memberikan kesan anggun. Warna bunganya yang mencolok namun tetap lembut membuat tanaman ini cocok sebagai penghias ruangan maupun teras.\n\nProduk ini cocok bagi pelanggan yang menyukai tanaman berbunga dengan warna yang lebih hidup. Anggrek Bulan Mini Purple dapat menjadi pilihan menarik untuk memperindah rumah sekaligus menambah nuansa alami.",
            ],
            [
                'name' => 'Anggrek Bulan Black Jack',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 150000,
                'old_price' => null,
                'image_url' => '/images/products/Anggrek Bulan Black Jack Clean.png',
                'stock' => 7,
                'rating' => 5.0,
                'reviews_count' => 11,
                'description' => "Anggrek Bulan Black Jack merupakan tanaman anggrek dengan tampilan bunga yang unik dan elegan. Warna bunganya yang lebih kuat memberikan kesan eksklusif serta berbeda dari jenis anggrek bulan pada umumnya.\n\nTanaman ini cocok untuk pelanggan yang menginginkan koleksi anggrek dengan karakter visual yang lebih menonjol. Dengan tampilan yang menarik, Anggrek Bulan Black Jack dapat menjadi pusat perhatian dalam dekorasi tanaman hias.",
            ],
            [
                'name' => 'Anggrek Cattleya Pra-Remaja',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Anggrek',
                'price' => 60000,
                'old_price' => null,
                'image_url' => '/images/products/Anggrek Cattleya Pra-Remaja Clean.png',
                'stock' => 18,
                'rating' => 4.3,
                'reviews_count' => 7,
                'description' => "Anggrek Cattleya Pra-Remaja merupakan tanaman anggrek yang masih berada pada fase pertumbuhan sebelum dewasa. Jenis ini cocok bagi pelanggan yang ingin merawat anggrek dari tahap awal hingga berkembang dan berbunga.\n\nProduk ini sesuai untuk penghobi tanaman yang menikmati proses perawatan tanaman hias. Dengan perawatan yang sabar dan tepat, Anggrek Cattleya Pra-Remaja dapat tumbuh menjadi tanaman anggrek yang indah dan bernilai dekoratif.",
            ],

            // =========================================================================
            // SUB-KATEGORI: Mawar (Kategori: Tanaman Berbunga) - 6 produk
            // =========================================================================
            [
                'name' => 'Mawar Impor Emilien',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 45000,
                'old_price' => 75000,
                'image_url' => '/images/products/Mawar Impor Emilien Clean.png',
                'stock' => 10,
                'rating' => 4.8,
                'reviews_count' => 19,
                'description' => "Mawar Impor Emilien merupakan tanaman mawar dengan tampilan bunga yang indah dan elegan. Warna serta bentuk kelopaknya memberikan kesan romantis, sehingga cocok digunakan sebagai tanaman hias di taman atau halaman rumah.\n\nProduk ini cocok untuk pelanggan yang ingin mempercantik area outdoor dengan tanaman berbunga. Mawar Impor Emilien dapat menjadi pilihan koleksi mawar yang menarik karena tampilannya memberikan kesan mewah dan alami.",
            ],
            [
                'name' => 'Blue Moonstone Rose',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 75000,
                'old_price' => null,
                'image_url' => '/images/products/Blue Moonstone Rose Clean.png',
                'stock' => 12,
                'rating' => 4.9,
                'reviews_count' => 13,
                'description' => "Blue Moonstone Rose merupakan tanaman mawar dengan tampilan bunga yang unik dan menarik. Keindahan warnanya membuat tanaman ini cocok dijadikan koleksi bagi pecinta mawar yang menginginkan variasi berbeda dari mawar biasa.\n\nTanaman ini dapat mempercantik taman, pot hias, maupun sudut halaman rumah. Blue Moonstone Rose sesuai untuk pelanggan yang menyukai tanaman berbunga dengan karakter visual yang lembut, cantik, dan estetik.",
            ],
            [
                'name' => 'Mawar Impor Kahala',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 40000,
                'old_price' => null,
                'image_url' => '/images/products/Mawar Impor Kahala Clean.png',
                'stock' => 15,
                'rating' => 4.5,
                'reviews_count' => 10,
                'description' => "Mawar Impor Kahala memiliki tampilan bunga yang cantik dengan warna yang memberikan kesan hangat dan elegan. Jenis mawar ini cocok untuk memperindah taman rumah maupun area dekorasi luar ruangan.\n\nProduk ini cocok bagi pelanggan yang ingin memiliki tanaman berbunga dengan daya tarik visual tinggi. Dengan perawatan yang baik, Mawar Impor Kahala dapat tumbuh indah dan memberikan suasana taman yang lebih hidup.",
            ],
            [
                'name' => 'Mawar Impor Aube',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 40000,
                'old_price' => null,
                'image_url' => '/images/products/Mawar Impor Aube Clean.png',
                'stock' => 10,
                'rating' => 4.7,
                'reviews_count' => 16,
                'description' => "Mawar Impor Aube merupakan jenis mawar yang memiliki tampilan bunga menawan dan cocok untuk koleksi tanaman hias berbunga. Bentuk kelopaknya memberikan kesan lembut, anggun, dan bernilai dekoratif.\n\nTanaman ini cocok diletakkan di taman, halaman, atau pot hias. Mawar Impor Aube dapat menjadi pilihan bagi pelanggan yang ingin menghadirkan nuansa romantis dan alami di lingkungan rumah.",
            ],
            [
                'name' => 'Mawar Impor Minion Putih',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 35000,
                'old_price' => null,
                'image_url' => '/images/products/Mawar Impor Minion Putih Clean.png',
                'stock' => 8,
                'rating' => 4.4,
                'reviews_count' => 5,
                'description' => "Mawar Impor Minion Putih memiliki bunga berwarna putih yang memberikan kesan bersih, lembut, dan elegan. Warna putih pada bunga mawar ini cocok untuk menciptakan suasana taman yang tenang dan indah.\n\nProduk ini sesuai untuk pelanggan yang menyukai tanaman berbunga dengan tampilan sederhana namun tetap menarik. Mawar Impor Minion Putih dapat menjadi pilihan dekorasi taman yang cantik dan mudah dipadukan dengan tanaman lain.",
            ],
            [
                'name' => 'Mawar Rambat Orange',
                'category' => 'Tanaman Berbunga',
                'subcategory' => 'Mawar',
                'price' => 45000,
                'old_price' => null,
                'image_url' => '/images/products/Mawar Rambat Orange Clean.png',
                'stock' => 6,
                'rating' => 4.6,
                'reviews_count' => 8,
                'description' => "Mawar Rambat Orange merupakan tanaman mawar rambat dengan warna bunga oranye yang cerah dan menarik. Jenis ini cocok digunakan untuk menghiasi pagar, dinding taman, pergola, atau area luar ruangan lainnya.\n\nTanaman ini sesuai untuk pelanggan yang ingin membuat taman terlihat lebih hidup dan berwarna. Dengan pertumbuhan yang merambat, Mawar Rambat Orange dapat menjadi elemen dekoratif alami yang mempercantik area rumah.",
            ],

            // =========================================================================
            // SUB-KATEGORI: Mangga (Kategori: Bibit Buah) - 6 produk
            // =========================================================================
            [
                'name' => 'Mangga Irwin (Jumbo)',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 600000,
                'old_price' => null,
                'image_url' => '/images/products/Mangga Irwin (Jumbo) Clean.png',
                'stock' => 2,
                'rating' => 5.0,
                'reviews_count' => 4,
                'description' => "Mangga Irwin Jumbo merupakan bibit mangga yang dikenal dengan ukuran buah yang besar dan tampilan menarik. Bibit ini cocok untuk ditanam di halaman rumah, kebun, maupun lahan pekarangan yang cukup luas.\n\nProduk ini sesuai untuk pelanggan yang ingin menanam tanaman buah produktif. Dengan perawatan yang tepat, Mangga Irwin Jumbo berpotensi menghasilkan buah yang dapat dikonsumsi sendiri maupun dimanfaatkan sebagai hasil kebun.",
            ],
            [
                'name' => 'Mangga Kiojay (Berbuah)',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 700000,
                'old_price' => null,
                'image_url' => '/images/products/Mangga Kiojay (Berbuah) Clean.png',
                'stock' => 3,
                'rating' => 4.9,
                'reviews_count' => 7,
                'description' => "Mangga Kiojay Berbuah merupakan bibit mangga yang sudah berada pada fase siap atau mendekati masa berbuah. Produk ini cocok bagi pelanggan yang ingin memiliki tanaman buah tanpa menunggu terlalu lama dari tahap bibit kecil.\n\nTanaman ini dapat menjadi pilihan menarik untuk pekarangan rumah karena memiliki nilai produktif dan dekoratif. Selain memperindah halaman, Mangga Kiojay Berbuah juga memberikan manfaat berupa hasil buah ketika sudah tumbuh optimal.",
            ],
            [
                'name' => 'Mangga Mahatir',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 90000,
                'old_price' => null,
                'image_url' => '/images/products/Mangga Mahatir Clean.png',
                'stock' => 15,
                'rating' => 4.7,
                'reviews_count' => 13,
                'description' => "Mangga Mahatir merupakan salah satu jenis bibit mangga yang banyak diminati karena potensi buahnya yang menarik. Bibit ini cocok ditanam di area pekarangan, kebun kecil, atau lahan terbuka dengan pencahayaan cukup.\n\nProduk ini sesuai untuk pelanggan yang ingin mulai berkebun tanaman buah. Dengan perawatan rutin seperti penyiraman, pemupukan, dan pencahayaan yang baik, Mangga Mahatir dapat tumbuh menjadi tanaman buah yang produktif.",
            ],
            [
                'name' => 'Mangga Apel',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 75000,
                'old_price' => 90000,
                'image_url' => '/images/products/Mangga Apel Clean.png',
                'stock' => 10,
                'rating' => 4.5,
                'reviews_count' => 11,
                'description' => "Mangga Apel merupakan bibit mangga dengan karakter buah yang khas dan berbeda dari jenis mangga lainnya. Tanaman ini cocok untuk pelanggan yang ingin memiliki variasi tanaman buah di halaman rumah.\n\nBibit Mangga Apel dapat menjadi pilihan untuk penghijauan sekaligus tanaman produktif. Selain memberikan suasana hijau pada lingkungan, tanaman ini juga berpotensi menghasilkan buah yang dapat dinikmati saat masa panen.",
            ],
            [
                'name' => 'Mangga Gajah',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 128000,
                'old_price' => 160000,
                'image_url' => '/images/products/Mangga Gajah Clean.png',
                'stock' => 8,
                'rating' => 4.6,
                'reviews_count' => 6,
                'description' => "Mangga Gajah merupakan jenis bibit mangga yang dikenal dengan potensi ukuran buah yang besar. Tanaman ini cocok ditanam di pekarangan atau kebun yang memiliki ruang tumbuh cukup luas.\n\nProduk ini sesuai untuk pelanggan yang ingin menanam tanaman buah bernilai produktif. Dengan perawatan yang baik, Mangga Gajah dapat tumbuh kuat dan menjadi pilihan tanaman buah yang bermanfaat untuk jangka panjang.",
            ],
            [
                'name' => 'Mangga Kiojay',
                'category' => 'Bibit Buah',
                'subcategory' => 'Mangga',
                'price' => 120000,
                'old_price' => 150000,
                'image_url' => '/images/products/Mangga Kiojay Clean.png',
                'stock' => 12,
                'rating' => 4.8,
                'reviews_count' => 9,
                'description' => "Mangga Kiojay merupakan bibit mangga yang cocok untuk ditanam sebagai tanaman buah di rumah maupun kebun. Jenis ini banyak diminati karena memiliki potensi buah yang menarik dan cocok untuk koleksi tanaman produktif.\n\nTanaman ini cocok untuk pelanggan yang ingin memanfaatkan lahan kosong menjadi lebih bermanfaat. With pemeliharaan yang tepat, Mangga Kiojay dapat tumbuh sehat dan memberikan hasil buah di kemudian hari.",
            ],

            // =========================================================================
            // SUB-KATEGORI: Media Tanam (Kategori: Produk Lain) - 6 produk
            // =========================================================================
            [
                'name' => 'Media Tanam Forest Moss 250gr',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 20000,
                'old_price' => null,
                'image_url' => '/images/products/Media Tanam Forest Moss 250gr Clean.png',
                'stock' => 50,
                'rating' => 4.8,
                'reviews_count' => 32,
                'description' => "Media Tanam Forest Moss 250gr merupakan media tanam yang dapat membantu menjaga kelembapan pada tanaman. Produk ini cocok digunakan untuk berbagai kebutuhan tanaman hias, terutama tanaman yang memerlukan media lembap.\n\nMedia ini sesuai untuk pelanggan yang ingin meningkatkan kualitas perawatan tanaman. Dengan penggunaan yang tepat, Forest Moss dapat membantu akar tanaman tetap sehat dan mendukung pertumbuhan tanaman secara optimal.",
            ],
            [
                'name' => 'Media Semai Premium 500gr',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 40000,
                'old_price' => null,
                'image_url' => '/images/products/Media Semai Premium 500gr Clean.png',
                'stock' => 40,
                'rating' => 4.7,
                'reviews_count' => 24,
                'description' => "Media Semai Premium 500gr merupakan media tanam yang dirancang untuk membantu proses penyemaian benih. Teksturnya mendukung pertumbuhan awal tanaman sehingga cocok digunakan oleh pemula maupun penghobi tanaman.\n\nProduk ini cocok untuk pelanggan yang ingin memulai proses menanam dari benih. Dengan media semai yang tepat, benih dapat tumbuh lebih baik dan lebih mudah dipindahkan ke media tanam utama setelah cukup kuat.",
            ],
            [
                'name' => 'Rockwool 15cm | Media Semai Benih',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 32000,
                'old_price' => null,
                'image_url' => '/images/products/Rockwall 15cm  Media Semai Benih Clean.png',
                'stock' => 100,
                'rating' => 4.6,
                'reviews_count' => 45,
                'description' => "Rockwool 15cm Media Semai Benih merupakan media semai yang praktis digunakan untuk menumbuhkan benih. Media ini banyak digunakan karena mampu menyerap air dengan baik dan mendukung proses perkecambahan.\n\nProduk ini cocok untuk penyemaian sayuran, tanaman hias, maupun kebutuhan hidroponik sederhana. Dengan bentuk yang mudah digunakan, Rockwool membantu proses semai menjadi lebih rapi dan efisien.",
            ],
            [
                'name' => 'Media Tanam Akadama 1 Karung',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 370000,
                'old_price' => null,
                'image_url' => '/images/products/Media Tanam Akadama 1 Karung Clean.png',
                'stock' => 5,
                'rating' => 4.9,
                'reviews_count' => 10,
                'description' => "Media Tanam Akadama 1 Karung merupakan media tanam yang cocok digunakan untuk kebutuhan tanaman tertentu, terutama tanaman yang membutuhkan media berpori. Akadama membantu menjaga sirkulasi udara dan kelembapan pada akar.\n\nProduk ini sesuai untuk pelanggan yang membutuhkan media tanam dalam jumlah lebih banyak. Dengan ukuran satu karung, media ini cocok digunakan untuk koleksi tanaman, repotting, atau kebutuhan berkebun yang lebih besar.",
            ],
            [
                'name' => 'Media Tanam Premium AKADAMA',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 45000,
                'old_price' => null,
                'image_url' => '/images/products/Media Tanam Premium AKADAMA Clean.png',
                'stock' => 20,
                'rating' => 5.0,
                'reviews_count' => 2,
                'description' => "Media Tanam Premium AKADAMA merupakan media tanam berkualitas yang dapat mendukung pertumbuhan akar tanaman. Media ini memiliki struktur yang baik untuk menjaga keseimbangan air dan udara di sekitar akar.\n\nProduk ini cocok untuk pelanggan yang ingin memberikan media tanam lebih optimal pada tanaman koleksi. Dengan penggunaan yang sesuai, Premium Akadama dapat membantu tanaman tumbuh lebih sehat dan kuat.",
            ],
            [
                'name' => 'Media Tanam Kaktus Premium',
                'category' => 'Produk Lain',
                'subcategory' => 'Media Tanam',
                'price' => 40000,
                'old_price' => null,
                'image_url' => '/images/products/Media Tanam Kaktus Premium Clean.png',
                'stock' => 25,
                'rating' => 5.0,
                'reviews_count' => 14,
                'description' => "Media Tanam Kaktus Premium merupakan media tanam khusus yang cocok untuk tanaman kaktus dan sukulen. Media ini dirancang agar tidak terlalu menahan air sehingga dapat membantu mencegah akar tanaman mudah membusuk.\n\nProduk ini cocok untuk pelanggan yang merawat kaktus, sukulen, atau tanaman sejenis yang membutuhkan media kering dan porous. Dengan media yang sesuai, tanaman dapat tumbuh lebih sehat dan perawatannya menjadi lebih mudah.",
            ],
        ];

        // Insert products in batch
        $this->db->table('products')->insertBatch($data);
    }
}
